server:
  port: 9191
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
